apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact
  template:
    metadata:
      labels:
        app: contact
    spec:
      containers:
        - name: contact
          image: gngk1234/contact
